{
    
    'name':'MySchool',
    'version':'1.0',
    'author':'Smaidi Reda',
    'category':'ENSAH ERP',
    'sequence':1,
    'description':"Managing a school",
    'images':[''],
    'init_xml':[],
    'depends':[],
    'data':[
        'views/view_class.xml',
        'views/view_complaints.xml',
        'views/view_course.xml',
        'views/view_eleve.xml',
        'views/view_etablishement.xml',
        'views/view_exam_result.xml',
        'views/view_exam.xml',
        'views/view_speciality.xml',
        'views/view_room.xml',
        'views/view_person.xml',
        'views/view_module.xml',
        'views/view_professor.xml',
        'views/view_scholaryear.xml'
    ],
    'website':'',
    'update_xml':[],
    'js':[],
    'qweb':[],
    'css':[],
    'demo':[],
    'test':[],
    'images':[],
    'installable':True,
    'auto_install':True
}