from . import model_etablishement
from . import model_person
from . import model_class
from . import model_speciality
from . import model_level
from . import model_scholaryear
from . import model_professor
from . import model_parent
from . import model_eleve
from . import model_inscription
from . import model_timetable
from . import model_module
from . import model_exam
from . import model_exam_result
from . import model_course
from . import model_holiday
from . import model_room
from . import model_complaints